<!DOCTYPE html><html lang="en,zh-CN,default"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=2"><meta name="theme-color" content="#222"><meta name="generator" content="Hexo 4.2.0"><link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next-5bcbd18f4de3fa448e0451b020974c18.png"><link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-a9ba5cde09a0e0fcac70b9154c968b9d.png"><link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-6b57f39f26ac59770807046a93a0e34f.png"><link rel="mask-icon" href="/images/logo.svg" color="#222"><link rel="stylesheet" href="/css/main-fa79ff7d3f298c19622960cf4a07afad.css"><link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.min.css"><script id="hexo-configurations">var NexT=window.NexT||{},CONFIG={hostname:new URL("https://blog.wisdomgarden.com").hostname,root:"/",scheme:"Pisces",version:"7.6.0",exturl:!1,sidebar:{position:"left",display:"post",padding:18,offset:12,onmobile:!1},copycode:{enable:!1,show_result:!1,style:null},back2top:{enable:!0,sidebar:!1,scrollpercent:!1},bookmark:{enable:!1,color:"#222",save:"auto"},fancybox:!1,mediumzoom:!1,lazyload:!1,pangu:!1,algolia:{appID:"",apiKey:"",indexName:"",hits:{per_page:10},labels:{input_placeholder:"Search for Posts",hits_empty:"We didn't find any results for the search: ${query}",hits_stats:"${hits} results found in ${time} ms"}},localsearch:{enable:!1,trigger:"auto",top_n_per_article:1,unescape:!1,preload:!1},path:"",motion:{enable:!0,async:!1,transition:{post_block:"fadeIn",post_header:"slideDownIn",post_body:"slideDownIn",coll_header:"slideLeftIn",sidebar:"slideUpIn"}}}</script><meta name="description" content="本篇主要阐述如何使用 promise 的链式调用，从以下几点说起：经典回调地狱通常，我们可能会有这样的场景：我们创建一个文件，创建成功时做一些事情，失败时做一些事情。那么假设有这样一个异步创建文件的函数 createFile()，它有两个回调函数，一个回调函数是文件成功创建时的回调，另一个则是出现异常时的回调。如下：123456789function successCallback(result)"><meta property="og:type" content="article"><meta property="og:title" content="Using Promises"><meta property="og:url" content="https://blog.wisdomgarden.com/2019/12/29/Using%20Promises/"><meta property="og:site_name" content="WG Product Blog"><meta property="og:description" content="本篇主要阐述如何使用 promise 的链式调用，从以下几点说起：经典回调地狱通常，我们可能会有这样的场景：我们创建一个文件，创建成功时做一些事情，失败时做一些事情。那么假设有这样一个异步创建文件的函数 createFile()，它有两个回调函数，一个回调函数是文件成功创建时的回调，另一个则是出现异常时的回调。如下：123456789function successCallback(result)"><meta property="og:locale" content="en_US"><meta property="article:published_time" content="2019-12-29T02:02:40.000Z"><meta property="article:modified_time" content="2020-01-03T02:20:11.798Z"><meta property="article:author" content="WisdomGarden Product"><meta property="article:tag" content="promise"><meta property="article:tag" content="javascript"><meta name="twitter:card" content="summary"><link rel="canonical" href="https://blog.wisdomgarden.com/2019/12/29/Using%20Promises/"><script id="page-configurations">CONFIG.page={sidebar:"",isHome:!1,isPost:!0,isPage:!1,isArchive:!1}</script><title>Using Promises | WG Product Blog</title><script async src="https://www.googletagmanager.com/gtag/js?id=UA-154015352-1"></script><script>if(CONFIG.hostname===location.hostname){function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","UA-154015352-1")}</script><noscript><style>.sidebar-inner,.use-motion .brand,.use-motion .collection-header,.use-motion .comments,.use-motion .menu-item,.use-motion .pagination,.use-motion .post-block,.use-motion .post-body,.use-motion .post-header{opacity:initial}.use-motion .site-subtitle,.use-motion .site-title{opacity:initial;top:initial}.use-motion .logo-line-before i{left:initial}.use-motion .logo-line-after i{right:initial}</style></noscript></head><body itemscope itemtype="http://schema.org/WebPage"><div class="container use-motion"><div class="headband"></div><header class="header" itemscope itemtype="http://schema.org/WPHeader"><div class="header-inner"><div class="site-brand-container"><div class="site-meta"><div><a href="/" class="brand" rel="start"><span class="logo-line-before"><i></i></span> <span class="site-title">WG Product Blog</span> <span class="logo-line-after"><i></i></span></a></div></div><div class="site-nav-toggle"><div class="toggle" aria-label="Toggle navigation bar"><span class="toggle-line toggle-line-first"></span> <span class="toggle-line toggle-line-middle"></span> <span class="toggle-line toggle-line-last"></span></div></div></div><nav class="site-nav"><ul id="menu" class="menu"><li class="menu-item menu-item-home"><a href="/" rel="section"><i class="fa fa-fw fa-home"></i>Home</a></li><li class="menu-item menu-item-tags"><a href="/tags/" rel="section"><i class="fa fa-fw fa-tags"></i>Tags</a></li><li class="menu-item menu-item-categories"><a href="/categories/" rel="section"><i class="fa fa-fw fa-th"></i>Categories</a></li><li class="menu-item menu-item-archives"><a href="/archives/" rel="section"><i class="fa fa-fw fa-archive"></i>Archives</a></li></ul></nav></div></header><div class="back-to-top"><i class="fa fa-arrow-up"></i> <span>0%</span></div><main class="main"><div class="main-inner"><div class="content-wrap"><div class="content"><div class="posts-expand"><article itemscope itemtype="http://schema.org/Article" class="post-block" lang="en"><link itemprop="mainEntityOfPage" href="https://blog.wisdomgarden.com/2019/12/29/Using%20Promises/"><span hidden itemprop="author" itemscope itemtype="http://schema.org/Person"><meta itemprop="image" content="/images/avatar.gif"><meta itemprop="name" content="WisdomGarden Product"><meta itemprop="description" content="WisdomGarden Product Blog"></span><span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization"><meta itemprop="name" content="WG Product Blog"></span><header class="post-header"><h1 class="post-title" itemprop="name headline">Using Promises</h1><div class="post-meta"><span class="post-meta-item"><span class="post-meta-item-icon"><i class="fa fa-calendar-o"></i> </span><span class="post-meta-item-text">Posted on</span> <time title="Created: 2019-12-29 10:02:40" itemprop="dateCreated datePublished" datetime="2019-12-29T10:02:40+08:00">2019-12-29</time> </span><span id="/2019/12/29/Using%20Promises/" class="post-meta-item leancloud_visitors" data-flag-title="Using Promises" title="Views"><span class="post-meta-item-icon"><i class="fa fa-eye"></i> </span><span class="post-meta-item-text">Views: </span><span class="leancloud-visitors-count"></span> </span><span class="post-meta-item"><span class="post-meta-item-icon"><i class="fa fa-copyright"></i> </span><span class="post-meta-item-text">Author: </span><span>lichun</span></span></div></header><div class="post-body" itemprop="articleBody"><p>本篇主要阐述如何使用 <em>promise</em> 的链式调用，从以下几点说起：</p><ul><li><p>经典回调地狱</p><p>通常，我们可能会有这样的场景：我们创建一个文件，创建成功时做一些事情，失败时做一些事情。那么假设有这样一个异步创建文件的函数 <em>createFile()</em>，它有两个回调函数，一个回调函数是文件成功创建时的回调，另一个则是出现异常时的回调。如下：</p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">function successCallback(result) &#123;</span><br><span class="line">    console.log(&quot;create file success: &quot; + result);</span><br><span class="line">&#125;</span><br><span class="line">    </span><br><span class="line">function failureCallback(error) &#123;</span><br><span class="line">    console.log(&quot;create file failure: &quot; + error);</span><br><span class="line">&#125;</span><br><span class="line">    </span><br><span class="line">createFile(args, successCallback, failureCallback);</span><br></pre></td></tr></table></figure><p>因此，按照原来这种回调方式，在之前如果要想做多重的异步操作，有可能导致以下经典的回调地狱：</p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">doSomething(function(result) &#123;</span><br><span class="line">    doSecondThing(result, function(newResult) &#123;</span><br><span class="line">        doThirdThing(newResult, function(finalResult) &#123;</span><br><span class="line">            console.log(&#39;Got the final result: &#39; + finalResult);</span><br><span class="line">        &#125;, failureCallback);</span><br><span class="line">    &#125;, failureCallback);</span><br><span class="line">&#125;, failureCallback);</span><br></pre></td></tr></table></figure></li><li><p>使用 <em>promise</em> 链</p><p>先看这段代码：</p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">var promise &#x3D; doSomething();</span><br><span class="line">var promise2 &#x3D; promise.then(successCallback, failureCallback);</span><br></pre></td></tr></table></figure><p>上述<em>promise2</em>不仅表示<em>doSomething</em>函数的完成，也代表了传入的成功或者失败的<em>callback</em>的完成，两个<em>callback</em>有可能返回一个<em>Promise</em>对象，从而形成另一个异步操作。<br>所以由<em>promise2</em>新增的回调函数都会被依次排在由上一个<em>successCallback</em>或<em>failureCallback</em>执行后所返回的<em>Promise</em>对象的后面。</p><p>为了避免第一部分提到的经典回调地狱，利用上述特性，我们可以把回调绑定到被返回的<em>Promise</em>上，形成一个<em>Promise</em>链：</p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line">doSomething().then(function(result) &#123;</span><br><span class="line">    return doSecondThing(result);</span><br><span class="line">&#125;)</span><br><span class="line">.then(function(newResult) &#123;</span><br><span class="line">    return doThirdThing(newResult);</span><br><span class="line">&#125;)</span><br><span class="line">.then(function(finalResult) &#123;</span><br><span class="line">    console.log(&#39;Got the final result: &#39; + finalResult);</span><br><span class="line">&#125;)</span><br><span class="line">.catch(failureCallback);</span><br></pre></td></tr></table></figure><p>上述代码中，捕获错误函数里的 <em>catch(failureCallback)</em> 实际是 <em>then(null,failureCallback)</em> 的缩略形式，且每个.<em>then()</em>一定要有返回值，否则<em>callback</em>将无法获取上一个<em>Promise</em>的结果。</p><p>通常在代码执行过程中，一遇到异常抛出，<em>Promise</em>链就会停下来，直接调用链式中最近的<em>catch</em>处理程序来继续当前执行。</p><p>另外，关于promise链我们有以下约定：</p><pre><code>1.在本轮Javascript event loop（事件循环）运行完成 之前，回调函数是不会被调用的;

2.通过then()添加的回调函数总会被调用，即便它是在异步操作完成之后才被添加的函数。

3.通过多次调用then()，可以添加多个回调函数，它们会按照插入顺序一个接一个独立执行。</code></pre></li><li><p><em>catch</em> 的后续链式操作：</p><p>有可能会在链式操作中抛出一个失败之后，还继续进行下面的操作，也就是在使用一个<em>catch</em>之后，继续执行<em>promise</em>。</p><p>示例：</p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line">new Promise((resolve, reject) &#x3D;&gt; &#123;</span><br><span class="line">    console.log(&#39;init&#39;);</span><br><span class="line">    resolve();</span><br><span class="line">&#125;)</span><br><span class="line">.then(() &#x3D;&gt; &#123;</span><br><span class="line">    throw new Error(&#39;some error&#39;);</span><br><span class="line">    console.log(&#39;not execute&#39;);</span><br><span class="line">&#125;)</span><br><span class="line">.catch(() &#x3D;&gt; &#123;</span><br><span class="line">    console.log(&#39;execute catch&#39;);</span><br><span class="line">&#125;)</span><br><span class="line">.then(() &#x3D;&gt; &#123;</span><br><span class="line">    console.log(&#39;execute after catch&#39;);</span><br><span class="line">&#125;);</span><br></pre></td></tr></table></figure><p>输出结果：</p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">init</span><br><span class="line">execute catch</span><br><span class="line">execute after catch</span><br></pre></td></tr></table></figure></li><li><p>嵌套以及 <em>catch</em> 捕获错误的作用域限制</p><p>先看以下示例：</p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">doOneThing().then(() &#x3D;&gt; doAnotherThing()</span><br><span class="line">    .then((anotherResult) &#x3D;&gt; &#123;</span><br><span class="line">        doSomethingElse(anotherResult)</span><br><span class="line">    &#125;)</span><br><span class="line">    .catch((e) &#x3D;&gt; &#123;</span><br><span class="line">        console.log(&quot;another failure&quot; + e.message)</span><br><span class="line">    &#125;)</span><br><span class="line">)</span><br><span class="line">.then(() &#x3D;&gt; doSomethingAfterOne())</span><br><span class="line">.catch((e) &#x3D;&gt; &#123;</span><br><span class="line">    console.log(&quot;One failure: &quot; + e.message)&#125;</span><br><span class="line">);</span><br></pre></td></tr></table></figure><p>上述例子中，在第一处的<em>catch</em>只会捕获到<em>doAnotherThing</em>和<em>doSomethingElse</em>函数的错误。第二处的<em>catch</em>捕捉外部错误，诸如<em>doOneThing</em>以及<em>doSomethingAfterOne</em>等的函数错误。<br>且即使在第一处捕获到错误，后面的函数也会继续运行下去。</p><p>若能够合理利用<em>catch</em>的作用域，可实现高精度的错误捕获和修复。</p></li><li><p>多个 <em>promise</em> 的并行操作</p><p>1.可以使用<em>Promise.all()</em>，然后等多个操作全部结束后再进行下一步操作：</p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">Promise.all([func1(), func2(), func3()])</span><br><span class="line">.then(([result1, result2, result3]) &#x3D;&gt; &#123; &#x2F;* use result1, result2 and result3 *&#x2F; &#125;);</span><br></pre></td></tr></table></figure><p>2.如果需要保证执行的顺序，可使用：</p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">[func1, func2, func3].reduce((p, f) &#x3D;&gt; p.then(f), Promise.resolve())</span><br><span class="line">.then(result3 &#x3D;&gt; &#123; &#x2F;* use result3 *&#x2F; &#125;);</span><br></pre></td></tr></table></figure><p>上述代码中，<em>p</em> 为上一次调用回调返回的值，或者是提供的初始值(<em>initialValue</em>)，<em>f</em> 为数组正在处理中的元素。<br>相当于：<em>Promise.resolve().then(func1).then(func2).then(func3);</em></p></li></ul><ul><li><p>最后，提出几个使用 <em>promise</em> 链需要注意的点</p><pre><code>1.在then()里一定要有返回值。否则promise链条就会断了，不能保证函数同步执行；

2.不要使用不必要的嵌套。嵌套使用不当，可能会导致未捕获的错误；

3.不要忘了catch。若不使用catch，程序执行出错，难以发现错误的根源。而且在大多数浏览器中不能终止的Promise链里的rejection。</code></pre></li></ul><p>本篇参考自MDN文档，谢谢阅读。</p></div><footer class="post-footer"><div class="post-tags"><a href="/tags/promise/" rel="tag"># promise</a> <a href="/tags/javascript/" rel="tag"># javascript</a></div><div class="post-nav"><div class="post-nav-item"><a href="/2019/12/23/at-least-one-editorconfig-file-in-echo-project/" rel="prev" title="每个项目里至少得有一份 .editorconfig 文件"><i class="fa fa-chevron-left"></i> 每个项目里至少得有一份 .editorconfig 文件</a></div><div class="post-nav-item"><a href="/2019/12/29/angular8%E5%88%9D%E4%BD%93%E9%AA%8C/" rel="next" title="angular8初体验">angular8初体验 <i class="fa fa-chevron-right"></i></a></div></div></footer></article></div></div></div><div class="toggle sidebar-toggle"><span class="toggle-line toggle-line-first"></span> <span class="toggle-line toggle-line-middle"></span> <span class="toggle-line toggle-line-last"></span></div><aside class="sidebar"><div class="sidebar-inner"><ul class="sidebar-nav motion-element"><li class="sidebar-nav-toc">Table of Contents</li><li class="sidebar-nav-overview">Overview</li></ul><div class="post-toc-wrap sidebar-panel"></div><div class="site-overview-wrap sidebar-panel"><div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person"><p class="site-author-name" itemprop="name">WisdomGarden Product</p><div class="site-description" itemprop="description">WisdomGarden Product Blog</div></div><div class="site-state-wrap motion-element"><nav class="site-state"><div class="site-state-item site-state-posts"><a href="/archives/"><span class="site-state-item-count">11</span> <span class="site-state-item-name">posts</span></a></div><div class="site-state-item site-state-categories"><a href="/categories/"><span class="site-state-item-count">1</span> <span class="site-state-item-name">categories</span></a></div><div class="site-state-item site-state-tags"><a href="/tags/"><span class="site-state-item-count">7</span> <span class="site-state-item-name">tags</span></a></div></nav></div></div></div></aside><div id="sidebar-dimmer"></div></div></main><footer class="footer"><div class="footer-inner"><div class="copyright">&copy; <span itemprop="copyrightYear">2020</span> <span class="with-love"><i class="fa fa-user"></i> </span><span class="author" itemprop="copyrightHolder">WisdomGarden Product</span></div><script>function leancloudSelector(url) {
    return document.getElementById(url).querySelector('.leancloud-visitors-count');
  }
  if (CONFIG.page.isPost) {
    function addCount(Counter) {
      var visitors = document.querySelector('.leancloud_visitors');
      var url = visitors.getAttribute('id').trim();
      var title = visitors.getAttribute('data-flag-title').trim();

      Counter('get', `/classes/Counter?where=${JSON.stringify({ url })}`)
        .then(response => response.json())
        .then(({ results }) => {
          if (results.length > 0) {
            var counter = results[0];
              leancloudSelector(url).innerText = counter.time + 1;
            Counter('put', '/classes/Counter/' + counter.objectId, { time: { '__op': 'Increment', 'amount': 1 } })
              .then(response => response.json())
              .catch(error => {
                console.log('Failed to save visitor count', error);
              })
          } else {
              leancloudSelector(url).innerText = 'Counter not initialized! More info at console err msg.';
              console.error('ATTENTION! LeanCloud counter has security bug, see how to solve it here: https://github.com/theme-next/hexo-leancloud-counter-security. \n However, you can still use LeanCloud without security, by setting `security` option to `false`.');
            
          }
        })
        .catch(error => {
          console.log('LeanCloud Counter Error', error);
        });
    }
  } else {
    function showTime(Counter) {
      var visitors = document.querySelectorAll('.leancloud_visitors');
      var entries = [...visitors].map(element => {
        return element.getAttribute('id').trim();
      });

      Counter('get', `/classes/Counter?where=${JSON.stringify({ url: { '$in': entries } })}`)
        .then(response => response.json())
        .then(({ results }) => {
          if (results.length === 0) {
            document.querySelectorAll('.leancloud_visitors .leancloud-visitors-count').forEach(element => {
              element.innerText = 0;
            });
            return;
          }
          for (let item of results) {
            let { url, time } = item;
            leancloudSelector(url).innerText = time;
          }
          for (let url of entries) {
            var element = leancloudSelector(url);
            if (element.innerText == '') {
              element.innerText = 0;
            }
          }
        })
        .catch(error => {
          console.log('LeanCloud Counter Error', error);
        });
    }
  }

  fetch('https://app-router.leancloud.cn/2/route?appId=CP8WSyQWeQ5mmzmbSmnEWMEi-MdYXbMMI')
    .then(response => response.json())
    .then(({ api_server }) => {
      var Counter = (method, url, data) => {
        return fetch(`https://${api_server}/1.1${url}`, {
          method: method,
          headers: {
            'X-LC-Id': 'CP8WSyQWeQ5mmzmbSmnEWMEi-MdYXbMMI',
            'X-LC-Key': 'FDvJGLIS6IClTgCBJ6yhUTJG',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(data)
        });
      };
      if (CONFIG.page.isPost) {
        if (CONFIG.hostname !== location.hostname) return;
        addCount(Counter);
      } else if (document.querySelectorAll('.post-title-link').length >= 1) {
        showTime(Counter);
      }
    });</script></div></footer></div><script src="/lib/anime.min.js"></script><script src="/lib/velocity/velocity.min.js"></script><script src="/lib/velocity/velocity.ui.min.js"></script><script src="/js/utils-6cec7bbff5f7ac7b1a060ad2739fe0e4.js"></script><script src="/js/motion-db947fcb73053e43b03d60c0db8d0a3e.js"></script><script src="/js/schemes/pisces-d4ec3ab52f0ad1a1bce16ad322a14701.js"></script><script src="/js/next-boot-c47528c6b7d3020a3dfd391c262dfebd.js"></script></body></html>